name: Reusable CI/CD Pipeline

# reusable workflow
on:
  workflow_call:
    inputs:
      run_push:
        type: boolean
        required: false
        default: false


jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Uruchom moją własną akcję
        uses: ./.github/actions/check-files  # ścieżka do akcji
        with:
          file_to_check: 'Dockerfile'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Start services with Docker Compose
        run: |
          docker compose up -d --build
          echo "Czekam 15 sekund na start..."
          sleep 15
          docker compose ps -a
          docker compose logs web

      - name: Run Tests inside Docker
        run: docker compose exec -T web pytest

      - name: Tear down Docker Compose
        run: docker compose down

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          # Pushuj tylko jeśli wywołano przez push
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/nowatorski_projekt_ind:latest
