name: Reusable CI/CD Pipeline

# reusable workflow
on:
  workflow_call:
    inputs:
      run_push:
        type: boolean
        required: false
        default: false


jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Uruchom moją własną akcję
        uses: ./.github/actions/check-files  # ścieżka do akcji
        with:
          file_to_check: 'Dockerfile'

      - name: Start services with Docker Compose
        run: |
          docker compose up -d --build
          echo "Czekam 15 sekund na start..."
          sleep 15
          docker compose ps -a
          docker compose logs web

      - name: Run Tests inside Docker
        run: docker compose exec -T web pytest

      - name: Tear down Docker Compose
        run: docker compose down

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      
